import ".//globals.css";
import Providers from "./providers";
import Navbar from "../components/Navbar";
import Box from "@mui/material/Box";
import Typography from "@mui/material/Typography";
import {getCookie, getCurrentUser} from "./actions";
import '../envConfig.js'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

    async function loggedIn() {
        const cookie = await getCookie('authorization');

        return !!cookie?.value
    }

    const currentUser = await getCurrentUser();

    // const isLoggedIn = use(loggedIn())
    const isLoggedIn = true

    return (
    <html lang="en">
    <head>
        <title>Legion Events</title>
    </head>
    <body className="mb-24 bg-[#fafafa]">
    <Providers currentUser={currentUser}>
        <Box className="flex flex-col">
            <Navbar isLoggedIn={isLoggedIn}/>
            <Box className={"max-w-[1200px] mx-auto w-full"}>
                {children}
            </Box>
        </Box>
    </Providers>
    <footer>
        <Box className="flex justify-center">
            <Typography variant={"caption"} textAlign={"center"}>
                © 2025 Legion Events AUS
            </Typography>
        </Box>
    </footer>
    </body>
    </html>

  )
}
