import ".//globals.css";
import Providers from "./providers";
import Navbar from "../components/Navbar";
import Box from "@mui/material/Box";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="mb-24 bg-white">
        <Providers>
            <Box className="flex flex-col">
                <Navbar/>
                <div className="mt-16"/>
                {children}
            </Box>
        </Providers>
      </body>
    </html>
  )
}
